### ISSUE TITLE
Can not compile uaparser.c util

### ISSUE THREAD

**Issue by Globik** [Klowner/uap-c#1]
Libuaparser.a - is ok,
Libuaparser.0.1.0.so - is ok,
But the uaparser can't be compile:
Error: 
___uap_core_regexes_yaml, ___uap_core_regexes_yaml_len are undeclared.
How to be? What I'm missing here? From Where to get this expressions?

**Comment by Globik** [comment]
I look into the regexes.yaml.h file, but there are only uap_core_regexes_yaml,
 uap_core_regexes_yaml_len.

**Comment by Globik** [comment]
Three underscore on front!

**Comment by Globik** [comment]
Yes! I got it. Iv changed the header file for those variables.

**Comment by Klowner** [comment]
Sorry about that, I thought I had fixed that path. Does it require adjustment still?

**Comment by Globik** [comment]
Hm, yes, you can close this issue. Thank you for your great library.

**Comment by Globik** [comment]
What else I'v noticed that's makefile does not work properly. I must by hand in my console run the command xxd -i ../uap-core/regexes.yaml > .build/regexes.yaml.h from the root directory of uap-c
As regexes.yaml.h was empty.
After I runned xxd -i uap-core/regexes.yaml > .build/regexes.yaml.h (without two points up front the path) then header file is ok, is not empty. 
And there was no three underscores.

**Comment by Klowner** [comment]
I'll check that out, my makefile-fu is super rusty :) thanks for checking stuff out

**Comment by Globik** [comment]
I'v tried to write node.js addon(binding) based on this uap-c.
https://github.com/Globik/globibot/tree/master/n-api/buf/buf1
 Alas, the pure javascript implementation of uap-core is much much faster than the node.js addon I write.
But this C lib per se is shining in pure C-applications and environments. A very nice job.

**Comment by Klowner** [comment]
Thank you! Did you publish your javascript binding anywhere? I'd love to take look at it at least.

**Comment by Klowner** [comment]
Oh it's in your comment! The GitHub notification email stripped it out :)

**Comment by Globik** [comment]
In a repository , a link is above. Or here
https://github.com/Globik/globibot/blob/master/n-api/buf/buf1/buf.c
 Just experiment. Perfomance is bad. There a number of type conversations between c++ instances and javascript.
In a loop of 50 cycles addon gives ca 2000ms, vanilla javascript implementation of uap-core - 300ms.
Vanilla test.c 50 cycles gives one second.

**Comment by Klowner** [comment]
Did I read that right?
pure C: 50 cycles / ~1000ms
javascript uap-core: 50 cycles / ~300ms

**Comment by Globik** [comment]
Not right.
I mean , pure C 0,0001 ,  addon 0,85, pure javascript 0,60

**Comment by Klowner** [comment]
Oh wow, ok! Awesome, that's pretty quick. Thanks for running benchmarks :)
